[package]

name = "alt"
version = "2.4.0"
authors = [ "Andrew De Ponte <cyphactor@gmail.com>", "Brian Miller <brimil01@gmail.com>", "Russ Cloak <russcloak@gmail.com>" ]

[dependencies]

argparse = "0.2.1"
ignore = "0.3.1"
regex = "0.2.5"
lazy_static = "1"
