[package]

name = "alt"
version = "2.3.0"
authors = [ "Andrew De Ponte <cyphactor@gmail.com>", "Brian Miller <brimil01@gmail.com>", "Russ Cloak <russcloak@gmail.com>" ]

[dependencies]

argparse = "0.2.1"
glob = "0.2.11"
regex = "0.1.73"
